# Generated by Django 5.0.6 on 2024-07-13 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_user_registration_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='registration_date',
        ),
    ]
