# Generated by Django 5.0.6 on 2024-07-22 05:49

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_user_registration_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='TruckAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('truck_id', models.CharField(max_length=50)),
                ('assessment_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('damage_description', models.TextField()),
                ('image_url', models.URLField(max_length=255)),
                ('severity_score', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('estimated_repair_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('urgency_level', models.CharField(blank=True, choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=10, null=True)),
                ('priority_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
            ],
            options={
                'ordering': ['-priority_score', '-assessment_date'],
                'indexes': [models.Index(fields=['truck_id'], name='core_trucka_truck_i_5fd352_idx'), models.Index(fields=['-priority_score'], name='core_trucka_priorit_72600c_idx')],
            },
        ),
    ]
