# Generated by Django 5.0.6 on 2024-07-22 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_truckassessment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='truckassessment',
            name='assessment_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='truckassessment',
            name='image_url',
            field=models.TextField(),
        ),
    ]
