# Generated by Django 5.0.6 on 2024-07-22 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_truckassessment_assessment_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'regular'), (2, 'admin')], default=1),
        ),
    ]
