# Generated by Django 5.0.6 on 2024-07-25 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_truckassessment_priority_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='truckassessment',
            name='damages',
            field=models.JSONField(default=list),
        ),
    ]
