# Generated by Django 5.0.6 on 2024-07-25 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_truckassessment_damages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='truckassessment',
            name='damages',
            field=models.TextField(default='[]'),
        ),
    ]
