# Generated by Django 5.0.6 on 2024-07-25 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_truckassessment_damages'),
    ]

    operations = [
        migrations.AddField(
            model_name='truckassessment',
            name='priority_explanation',
            field=models.TextField(blank=True, null=True),
        ),
    ]
