# Generated by Django 5.0.6 on 2024-07-25 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_truckassessment_priority_explanation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='truckassessment',
            name='damages',
        ),
    ]
