# Generated by Django 5.0.6 on 2024-07-26 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_remove_truckassessment_damages'),
    ]

    operations = [
        migrations.AddField(
            model_name='truckassessment',
            name='damages',
            field=models.TextField(default='[]'),
        ),
    ]
