# Generated by Django 5.0.6 on 2024-07-31 10:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_truckassessment_damages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='truckassessment',
            name='damages',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='truckassessment',
            name='priority_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='truckassessment',
            name='severity_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
